name: iOS Build

on: push

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.3'
    - name: Installation of node
      uses: actions/setup-node@v3
      with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

    - name: npm install for SDK 
      run: npm install
    
    - name: npm install for example 
      run: |
        cd example
        npm install
        cd ..

    - name: Pod Install for iOS
      run: |
        cd example/ios
        pod install
        cd ../..
   