name: "publish"

on:
   push:
     branches: [ main ]

jobs:
  publish:
     name: publishing
     runs-on: ubuntu-latest

     steps:
        - name: checkout
          uses: actions/checkout@v3.0.2
        - name: installation of node
          uses: actions/setup-node@v4
          with:
            node-version: 20
            registry-url: 'https://registry.npmjs.org'

        - name: publish
          run: |
           npm install
           npm publish
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

